"""bgs

Revision ID: 0d9a5fd78147
Revises: bc3b1e9f2d03
Create Date: 2024-08-10 01:27:59.956614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9a5fd78147'
down_revision: Union[str, None] = 'bc3b1e9f2d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backgrounds', sa.Column('image_data', sa.String(), nullable=False))
    op.drop_column('backgrounds', 'image_id')
    op.add_column('boards', sa.Column('background_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'boards', 'backgrounds', ['background_id'], ['id'])
    op.drop_column('cards', 'deadline')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'background_id')
    op.add_column('backgrounds', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('backgrounds', 'image_data')
    # ### end Alembic commands ###
