"""bgs2

Revision ID: 752f3ad4d129
Revises: 0d9a5fd78147
Create Date: 2024-08-10 01:35:42.088120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752f3ad4d129'
down_revision: Union[str, None] = '0d9a5fd78147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deadline', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'deadline')
    # ### end Alembic commands ###
