"""added ordering

Revision ID: 7d8bb994d303
Revises: a61ae6e3ef6d
Create Date: 2024-06-30 13:52:58.973421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8bb994d303'
down_revision: Union[str, None] = 'a61ae6e3ef6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('ordering', sa.JSON(), nullable=False))
    op.drop_column('cards', 'ordering')
    op.add_column('spaces', sa.Column('ordering', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'ordering')
    op.add_column('cards', sa.Column('ordering', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('boards', 'ordering')
    # ### end Alembic commands ###
