"""deadline cards

Revision ID: 7fed969ac7ca
Revises: 5fcf8a3cdcb7
Create Date: 2024-08-07 23:34:44.266364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fed969ac7ca'
down_revision: Union[str, None] = '5fcf8a3cdcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deadline', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'deadline')
    # ### end Alembic commands ###
