"""aadd

Revision ID: bc3b1e9f2d03
Revises: 43b826336027
Create Date: 2024-08-08 00:34:05.665167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3b1e9f2d03'
down_revision: Union[str, None] = '43b826336027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('backgrounds_owner_id_fkey', 'backgrounds', type_='foreignkey')
    op.drop_column('backgrounds', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backgrounds', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('backgrounds_owner_id_fkey', 'backgrounds', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
