"""images

Revision ID: fe2f9d42fedd
Revises: b54daee0fa5f
Create Date: 2024-08-10 09:14:42.341086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2f9d42fedd'
down_revision: Union[str, None] = 'b54daee0fa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backgrounds', sa.Column('image_path', sa.String(), nullable=False))
    op.drop_column('backgrounds', 'image_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backgrounds', sa.Column('image_data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('backgrounds', 'image_path')
    # ### end Alembic commands ###
