version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: kanban_nginx
    ports:
      - 80:80
      - 443:443
    links:
      - kanban

  db:
    image: postgres:15
    container_name: kanban_db
#    volumes:
#      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-doc
    ports:
      - 5432:5432


  kanban:
    build:
      context: .
    container_name: kanban_app
    env_file:
      - .env-doc
    depends_on:
      - db

    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000

#volumes:
#  postgresdata:
